# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96d13b493f838b264c5909e2058f6cc9461d530d19f85100dde6f401894e4cef3edd1e94d256785be4dff0d8ef7a865d4ae15e23cd536cb74bada97e83487c5f

test:
  secret_key_base: ff212bce7eedf82de43db290a8da4491dd71a722146aa68d0ebee4b5dfdea580c3c8149eb6a3cc2a6cc270c0fb4f83293b0d1c3f9372b6b389e67a6e6fdbd957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
